seed: 1337
trainset: mxnet
train_root: ./datasets/train
num_classes: 85742
val_targets: ['lfw', 'agedb_30', 'cfp_ff', 'cfp_fp', 'cplfw', 'calfw', 'vgg2_fp']
val_root: ./datasets/val
epochs: 2
lr: 0.001
lr_func: none
batch_size: 128
bw_step: 1
weight_decay: 0.0005
momentum: 0.9
shuffle: False
criterion: crossentropy
header: ArcFace
m: 0.5
s: 64.0
std: 0.05
SE: False
log_freq: 50
cp_freq: 1
val_freq: 1
qepoch: none
finetune_epoch: none
wq: none
aq: none
qfunc: kmeans
num_colors: 32
network: mobilefacenet
embedding_size: 128
output: ./output/kmeans/mobilefacenet_fp32/32
